#!/bin/bash

set -e
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
CHANGE MASTER TO MASTER_HOST='$MASTER_HOST',MASTER_USER='$DB_MASTER_USER',MASTER_PASSWORD='$DB_MASTER_PWD',MASTER_AUTO_POSITION=1;
START SLAVE;
EOSQL