#!/usr/bin/env sh
EMAIL_MUST_HAVE="@gmail.com"
PWD=$HOME
EMAIL=$(git config user.email)

if expr "x$EMAIL" : "x.*$EMAIL_MUST_HAVE" >/dev/null; then
	echo "[INFO] Verified email: $EMAIL"
else
	echo "[ERROR] Invalid email: $EMAIL => Please configure the company email and retry."
	echo "Steps:"
	echo "   cd $PWD"
	echo "   git config user.email '<user>'$EMAIL_MUST_HAVE"
	echo ""
	exit 1
fi
